CREATE TABLE components (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    pin INT,
    x DOUBLE PRECISION NOT NULL DEFAULT 0,
    y DOUBLE PRECISION NOT NULL DEFAULT 0,
    z DOUBLE PRECISION NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    rot_x DOUBLE PRECISION NOT NULL DEFAULT 0,
    rot_y DOUBLE PRECISION NOT NULL DEFAULT 0,
    rot_z DOUBLE PRECISION NOT NULL DEFAULT 0,
    colour VARCHAR(255),
    config JSONB NOT NULL DEFAULT '{}'::jsonb
);