// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: animation_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnimationEvent = `-- name: CreateAnimationEvent :one
INSERT INTO animation_events (animation_id, component_id, trigger_time, action, easing)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, '0,0,1,1')
)
RETURNING id, animation_id, component_id, trigger_time, action, easing
`

type CreateAnimationEventParams struct {
	AnimationID int32       `json:"animation_id"`
	ComponentID int32       `json:"component_id"`
	TriggerTime float64     `json:"trigger_time"`
	Action      string      `json:"action"`
	Easing      interface{} `json:"easing"`
}

func (q *Queries) CreateAnimationEvent(ctx context.Context, arg CreateAnimationEventParams) (AnimationEvent, error) {
	row := q.db.QueryRow(ctx, createAnimationEvent,
		arg.AnimationID,
		arg.ComponentID,
		arg.TriggerTime,
		arg.Action,
		arg.Easing,
	)
	var i AnimationEvent
	err := row.Scan(
		&i.ID,
		&i.AnimationID,
		&i.ComponentID,
		&i.TriggerTime,
		&i.Action,
		&i.Easing,
	)
	return i, err
}

const deleteAnimationEvent = `-- name: DeleteAnimationEvent :execrows
DELETE FROM animation_events
WHERE id = $1
`

func (q *Queries) DeleteAnimationEvent(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnimationEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnimationEvent = `-- name: GetAnimationEvent :one
SELECT id, animation_id, component_id, trigger_time, action, easing FROM animation_events
WHERE id = $1
`

func (q *Queries) GetAnimationEvent(ctx context.Context, id int32) (AnimationEvent, error) {
	row := q.db.QueryRow(ctx, getAnimationEvent, id)
	var i AnimationEvent
	err := row.Scan(
		&i.ID,
		&i.AnimationID,
		&i.ComponentID,
		&i.TriggerTime,
		&i.Action,
		&i.Easing,
	)
	return i, err
}

const getAnimationEvents = `-- name: GetAnimationEvents :many
SELECT id, animation_id, component_id, trigger_time, action, easing FROM animation_events
ORDER BY trigger_time ASC
`

func (q *Queries) GetAnimationEvents(ctx context.Context) ([]AnimationEvent, error) {
	rows, err := q.db.Query(ctx, getAnimationEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnimationEvent
	for rows.Next() {
		var i AnimationEvent
		if err := rows.Scan(
			&i.ID,
			&i.AnimationID,
			&i.ComponentID,
			&i.TriggerTime,
			&i.Action,
			&i.Easing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnimationEventsByAnimation = `-- name: GetAnimationEventsByAnimation :many
SELECT id, animation_id, component_id, trigger_time, action, easing FROM animation_events
WHERE animation_id = $1
ORDER BY trigger_time ASC
`

func (q *Queries) GetAnimationEventsByAnimation(ctx context.Context, animationID int32) ([]AnimationEvent, error) {
	rows, err := q.db.Query(ctx, getAnimationEventsByAnimation, animationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnimationEvent
	for rows.Next() {
		var i AnimationEvent
		if err := rows.Scan(
			&i.ID,
			&i.AnimationID,
			&i.ComponentID,
			&i.TriggerTime,
			&i.Action,
			&i.Easing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnimationEvent = `-- name: UpdateAnimationEvent :one
UPDATE animation_events
SET
    animation_id  = COALESCE($1, animation_id),
    component_id  = COALESCE($2, component_id),
    trigger_time  = COALESCE($3, trigger_time),
    action        = COALESCE($4, action),
    easing        = COALESCE($5, easing)
WHERE id = $6
RETURNING id, animation_id, component_id, trigger_time, action, easing
`

type UpdateAnimationEventParams struct {
	AnimationID pgtype.Int4   `json:"animation_id"`
	ComponentID pgtype.Int4   `json:"component_id"`
	TriggerTime pgtype.Float8 `json:"trigger_time"`
	Action      pgtype.Text   `json:"action"`
	Easing      pgtype.Text   `json:"easing"`
	ID          int32         `json:"id"`
}

func (q *Queries) UpdateAnimationEvent(ctx context.Context, arg UpdateAnimationEventParams) (AnimationEvent, error) {
	row := q.db.QueryRow(ctx, updateAnimationEvent,
		arg.AnimationID,
		arg.ComponentID,
		arg.TriggerTime,
		arg.Action,
		arg.Easing,
		arg.ID,
	)
	var i AnimationEvent
	err := row.Scan(
		&i.ID,
		&i.AnimationID,
		&i.ComponentID,
		&i.TriggerTime,
		&i.Action,
		&i.Easing,
	)
	return i, err
}
