// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: animations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnimation = `-- name: CreateAnimation :one
INSERT INTO animations (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateAnimation(ctx context.Context, name string) (Animation, error) {
	row := q.db.QueryRow(ctx, createAnimation, name)
	var i Animation
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteAnimation = `-- name: DeleteAnimation :execrows
DELETE FROM animations
WHERE id = $1
`

func (q *Queries) DeleteAnimation(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnimation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnimation = `-- name: GetAnimation :one
SELECT id, name FROM animations
WHERE id = $1
`

func (q *Queries) GetAnimation(ctx context.Context, id int32) (Animation, error) {
	row := q.db.QueryRow(ctx, getAnimation, id)
	var i Animation
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAnimations = `-- name: GetAnimations :many
SELECT id, name FROM animations
`

func (q *Queries) GetAnimations(ctx context.Context) ([]Animation, error) {
	rows, err := q.db.Query(ctx, getAnimations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Animation
	for rows.Next() {
		var i Animation
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnimation = `-- name: UpdateAnimation :one
UPDATE animations
SET 
    name = COALESCE($1, name)
WHERE id = $2
RETURNING id, name
`

type UpdateAnimationParams struct {
	Name pgtype.Text `json:"name"`
	ID   int32       `json:"id"`
}

func (q *Queries) UpdateAnimation(ctx context.Context, arg UpdateAnimationParams) (Animation, error) {
	row := q.db.QueryRow(ctx, updateAnimation, arg.Name, arg.ID)
	var i Animation
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
