// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    type,
    name,
    colour,
    config
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, type, name, colour, config
`

type CreateAssetParams struct {
	Type   string          `json:"type"`
	Name   string          `json:"name"`
	Colour string          `json:"colour"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Type,
		arg.Name,
		arg.Colour,
		arg.Config,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Colour,
		&i.Config,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :execrows
DELETE FROM assets
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAsset = `-- name: GetAsset :one
SELECT id, type, name, colour, config
FROM assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id int32) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Colour,
		&i.Config,
	)
	return i, err
}

const getAssets = `-- name: GetAssets :many
SELECT id, type, name, colour, config FROM assets
ORDER BY id
`

func (q *Queries) GetAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Colour,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET
    type = COALESCE($1, type),
    name = COALESCE($2, name),
    colour = COALESCE($3, colour),
    config = COALESCE($4, config)
WHERE id = $5
RETURNING id, type, name, colour, config
`

type UpdateAssetParams struct {
	Type   pgtype.Text     `json:"type"`
	Name   pgtype.Text     `json:"name"`
	Colour pgtype.Text     `json:"colour"`
	Config json.RawMessage `json:"config"`
	ID     int32           `json:"id"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.Type,
		arg.Name,
		arg.Colour,
		arg.Config,
		arg.ID,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Colour,
		&i.Config,
	)
	return i, err
}
