// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (
    type,
    pin,
    name,
    colour,
    config
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, type, pin, x, y, z, name, rot_x, rot_y, rot_z, colour, config
`

type CreateComponentParams struct {
	Type   string          `json:"type"`
	Pin    pgtype.Int4     `json:"pin"`
	Name   string          `json:"name"`
	Colour pgtype.Text     `json:"colour"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.Type,
		arg.Pin,
		arg.Name,
		arg.Colour,
		arg.Config,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Pin,
		&i.X,
		&i.Y,
		&i.Z,
		&i.Name,
		&i.RotX,
		&i.RotY,
		&i.RotZ,
		&i.Colour,
		&i.Config,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :execrows
DELETE FROM components
WHERE id = $1
`

func (q *Queries) DeleteComponent(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComponent = `-- name: GetComponent :one
SELECT id, type, pin, x, y, z, name, rot_x, rot_y, rot_z, colour, config FROM components
WHERE id = $1
`

func (q *Queries) GetComponent(ctx context.Context, id int32) (Component, error) {
	row := q.db.QueryRow(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Pin,
		&i.X,
		&i.Y,
		&i.Z,
		&i.Name,
		&i.RotX,
		&i.RotY,
		&i.RotZ,
		&i.Colour,
		&i.Config,
	)
	return i, err
}

const getComponents = `-- name: GetComponents :many
SELECT id, type, pin, x, y, z, name, rot_x, rot_y, rot_z, colour, config FROM components
`

func (q *Queries) GetComponents(ctx context.Context) ([]Component, error) {
	rows, err := q.db.Query(ctx, getComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Pin,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Name,
			&i.RotX,
			&i.RotY,
			&i.RotZ,
			&i.Colour,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComponentsWithAnimations = `-- name: GetComponentsWithAnimations :many
SELECT
  c.id,
  c.type,
  c.pin,
  c.x,
  c.y,
  c.z,
  c.name,
  c.rot_x,
  c.rot_y,
  c.rot_z,
  c.colour,
  c.config,
  COALESCE(
      jsonb_agg(to_jsonb(ae)) FILTER (WHERE ae.id IS NOT NULL),
      '[]'::jsonb
  )::jsonb AS animation_events
FROM components c
LEFT JOIN animation_events ae ON ae.component_id = c.id
GROUP BY c.id
ORDER BY c.id
`

type GetComponentsWithAnimationsRow struct {
	ID              int32           `json:"id"`
	Type            string          `json:"type"`
	Pin             pgtype.Int4     `json:"pin"`
	X               float64         `json:"x"`
	Y               float64         `json:"y"`
	Z               float64         `json:"z"`
	Name            string          `json:"name"`
	RotX            float64         `json:"rot_x"`
	RotY            float64         `json:"rot_y"`
	RotZ            float64         `json:"rot_z"`
	Colour          pgtype.Text     `json:"colour"`
	Config          json.RawMessage `json:"config"`
	AnimationEvents json.RawMessage `json:"animation_events"`
}

func (q *Queries) GetComponentsWithAnimations(ctx context.Context) ([]GetComponentsWithAnimationsRow, error) {
	rows, err := q.db.Query(ctx, getComponentsWithAnimations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComponentsWithAnimationsRow
	for rows.Next() {
		var i GetComponentsWithAnimationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Pin,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Name,
			&i.RotX,
			&i.RotY,
			&i.RotZ,
			&i.Colour,
			&i.Config,
			&i.AnimationEvents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components
SET
    type   = COALESCE($1, type),
    pin    = COALESCE($2, pin),
    x      = COALESCE($3, x),
    y      = COALESCE($4, y),
    z      = COALESCE($5, z),
    name   = COALESCE($6, name),
    rot_x  = COALESCE($7, rot_x),
    rot_y  = COALESCE($8, rot_y),
    rot_z  = COALESCE($9, rot_z),
    colour = COALESCE($10, colour),
    config = COALESCE($11, config)
WHERE id = $12
RETURNING id, type, pin, x, y, z, name, rot_x, rot_y, rot_z, colour, config
`

type UpdateComponentParams struct {
	Type   pgtype.Text   `json:"type"`
	Pin    pgtype.Int4   `json:"pin"`
	X      pgtype.Float8 `json:"x"`
	Y      pgtype.Float8 `json:"y"`
	Z      pgtype.Float8 `json:"z"`
	Name   pgtype.Text   `json:"name"`
	RotX   pgtype.Float8 `json:"rot_x"`
	RotY   pgtype.Float8 `json:"rot_y"`
	RotZ   pgtype.Float8 `json:"rot_z"`
	Colour pgtype.Text   `json:"colour"`
	Config []byte        `json:"config"`
	ID     int32         `json:"id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.Type,
		arg.Pin,
		arg.X,
		arg.Y,
		arg.Z,
		arg.Name,
		arg.RotX,
		arg.RotY,
		arg.RotZ,
		arg.Colour,
		arg.Config,
		arg.ID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Pin,
		&i.X,
		&i.Y,
		&i.Z,
		&i.Name,
		&i.RotX,
		&i.RotY,
		&i.RotZ,
		&i.Colour,
		&i.Config,
	)
	return i, err
}
