// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Animation struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type AnimationEvent struct {
	ID          int32       `json:"id"`
	AnimationID int32       `json:"animation_id"`
	ComponentID int32       `json:"component_id"`
	TriggerTime float64     `json:"trigger_time"`
	Action      string      `json:"action"`
	Easing      pgtype.Text `json:"easing"`
}

type Asset struct {
	ID     int32           `json:"id"`
	Type   string          `json:"type"`
	Name   string          `json:"name"`
	Colour string          `json:"colour"`
	Config json.RawMessage `json:"config"`
}

type Component struct {
	ID     int32           `json:"id"`
	Type   string          `json:"type"`
	Pin    pgtype.Int4     `json:"pin"`
	X      float64         `json:"x"`
	Y      float64         `json:"y"`
	Z      float64         `json:"z"`
	Name   string          `json:"name"`
	RotX   float64         `json:"rot_x"`
	RotY   float64         `json:"rot_y"`
	RotZ   float64         `json:"rot_z"`
	Colour pgtype.Text     `json:"colour"`
	Config json.RawMessage `json:"config"`
}

type Module struct {
	ID      int32  `json:"id"`
	Type    string `json:"type"`
	Address string `json:"address"`
	Name    string `json:"name"`
}
