// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModule = `-- name: CreateModule :one
INSERT INTO modules (address, type, name)
VALUES ($1, $2, $3)
RETURNING id, type, address, name
`

type CreateModuleParams struct {
	Address string `json:"address"`
	Type    string `json:"type"`
	Name    string `json:"name"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule, arg.Address, arg.Type, arg.Name)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Address,
		&i.Name,
	)
	return i, err
}

const deleteModule = `-- name: DeleteModule :execrows
DELETE FROM modules
WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getModule = `-- name: GetModule :one
SELECT id, type, address, name FROM modules
WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id int32) (Module, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Address,
		&i.Name,
	)
	return i, err
}

const getModules = `-- name: GetModules :many
SELECT id, type, address, name FROM modules
`

func (q *Queries) GetModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.Query(ctx, getModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Address,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET 
    name = COALESCE($1, name),
    "type" = COALESCE($2, type),
    address = COALESCE($3, address)
WHERE id = $4
RETURNING id, type, address, name
`

type UpdateModuleParams struct {
	Name    pgtype.Text `json:"name"`
	Type    pgtype.Text `json:"type"`
	Address pgtype.Text `json:"address"`
	ID      int32       `json:"id"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.Name,
		arg.Type,
		arg.Address,
		arg.ID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Address,
		&i.Name,
	)
	return i, err
}
