// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateAnimation(ctx context.Context, name string) (Animation, error)
	CreateAnimationEvent(ctx context.Context, arg CreateAnimationEventParams) (AnimationEvent, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	DeleteAnimation(ctx context.Context, id int32) (int64, error)
	DeleteAnimationEvent(ctx context.Context, id int32) (int64, error)
	DeleteAsset(ctx context.Context, id int32) (int64, error)
	DeleteComponent(ctx context.Context, id int32) (int64, error)
	DeleteModule(ctx context.Context, id int32) (int64, error)
	GetAnimation(ctx context.Context, id int32) (Animation, error)
	GetAnimationEvent(ctx context.Context, id int32) (AnimationEvent, error)
	GetAnimationEvents(ctx context.Context) ([]AnimationEvent, error)
	GetAnimationEventsByAnimation(ctx context.Context, animationID int32) ([]AnimationEvent, error)
	GetAnimations(ctx context.Context) ([]Animation, error)
	GetAsset(ctx context.Context, id int32) (Asset, error)
	GetAssets(ctx context.Context) ([]Asset, error)
	GetComponent(ctx context.Context, id int32) (Component, error)
	GetComponents(ctx context.Context) ([]Component, error)
	GetComponentsWithAnimations(ctx context.Context) ([]GetComponentsWithAnimationsRow, error)
	GetModule(ctx context.Context, id int32) (Module, error)
	GetModules(ctx context.Context) ([]Module, error)
	UpdateAnimation(ctx context.Context, arg UpdateAnimationParams) (Animation, error)
	UpdateAnimationEvent(ctx context.Context, arg UpdateAnimationEventParams) (AnimationEvent, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error)
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error)
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
}

var _ Querier = (*Queries)(nil)
