name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Image
        run: |
          docker login --username isaacyu15 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build ./backend --tag ghcr.io/isaacyu15/robotics-animator-backend-ghcr:latest
          docker push ghcr.io/isaacyu15/robotics-animator-backend-ghcr:latest

      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
